/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/config/(.*)$",
    "^@/hooks/(.*)$",
    "^@/lib/(.*)$",
    "^@/types/(.*)$",
    "^@/styles/(.*)$",
    "",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/features/app/(.*)$/api",
    "^@/features/app/(.*)$/components",
    "^@/features/app/(.*)$/providers",
    "^@/features/app/(.*)$/stores",
    "^@/features/app/(.*)$/validators",
    "^@/features/auth/(.*)$/api",
    "^@/features/auth/(.*)$/components",
    "^@/features/auth/(.*)$/providers",
    "^@/features/auth/(.*)$/stores",
    "^@/features/auth/(.*)$/validators",
    "^@/features/(.*)$",
    "^@/pages/(.*)$",
    "^@/routes/(.*)$",
    "",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
}
